/nvblox_node:
  ros__parameters:
    after_shutdown_map_save_path: ''
    back_projection_subsampling: 1
    clear_map_outside_radius_rate_hz: 1.0
    cuda_stream_type: 1
    decay_dynamic_occupancy_rate_hz: 10.0
    decay_tsdf_rate_hz: 5.0
    distance_map_unknown_value_optimistic: 1000.0
    distance_map_unknown_value_pessimistic: -1000.0
    dynamic_mapper:
      check_neighborhood: true
      decay_integrator_deallocate_decayed_blocks: true
      depth_preprocessing_num_dilations: 4
      do_depth_preprocessing: false
      esdf_integrator_max_distance_m: 2.0
      esdf_integrator_max_site_distance_vox: 1.0
      esdf_integrator_min_weight: 9.999999747378752e-05
      esdf_slice_height: 1.0
      esdf_slice_max_height: 1.0
      esdf_slice_min_height: 0.0
      exclude_last_view_from_decay: false
      free_region_decay_probability: 0.550000011920929
      free_region_occupancy_probability: 0.30000001192092896
      lidar_projective_integrator_max_integration_distance_m: 10.0
      max_tsdf_distance_for_occupancy_m: 0.15000000596046448
      max_unobserved_to_keep_consecutive_occupancy_ms: 200
      mesh_integrator_min_weight: 9.999999747378752e-05
      mesh_integrator_weld_vertices: true
      min_consecutive_occupancy_duration_for_reset_ms: 2000
      min_duration_since_occupied_for_freespace_ms: 1000
      occupancy_decay_to_free: false
      occupied_region_decay_probability: 0.4000000059604645
      occupied_region_half_width_m: 0.10000000149011612
      occupied_region_occupancy_probability: 0.699999988079071
      projective_integrator_max_integration_distance_m: 7.0
      projective_integrator_max_weight: 5.0
      projective_integrator_truncation_distance_vox: 4.0
      projective_integrator_weighting_mode: kInverseSquareWeight
      projective_tsdf_integrator_invalid_depth_decay_factor: -1.0
      raycast_subsampling_factor: 4
      slice_height_above_plane_m: 0.0
      slice_height_thickness_m: 0.10000000149011612
      tsdf_decay_factor: 0.949999988079071
      tsdf_decayed_free_distance_vox: 4.0
      tsdf_decayed_weight_threshold: 0.0010000000474974513
      tsdf_set_free_distance_on_decayed: false
      unobserved_region_occupancy_probability: 0.5
      workspace_bounds_max_corner_x_m: 0.0
      workspace_bounds_max_corner_y_m: 2.0
      workspace_bounds_max_height_m: 1.0
      workspace_bounds_min_corner_x_m: 0.0
      workspace_bounds_min_corner_y_m: 2.0
      workspace_bounds_min_height_m: 0.0
      workspace_bounds_type: kUnbounded
    esdf_and_gradients_unobserved_value: -1000.0
    esdf_mode: 2d
    esdf_slice_bounds_visualization_attachment_frame_id: base_link
    esdf_slice_bounds_visualization_side_length: 10.0
    global_frame: odom
    ground_plane_visualization_attachment_frame_id: base_link
    ground_plane_visualization_side_length: 10.0
    input_qos: SYSTEM_DEFAULT
    input_qos_depth: 0
    integrate_color_rate_hz: 5.0
    integrate_depth_rate_hz: 40.0
    integrate_lidar_rate_hz: 40.0
    layer_streamer_bandwidth_limit_mbps: 30.0
    layer_visualization_exclusion_height_m: 2.0
    layer_visualization_exclusion_radius_m: 5.0
    layer_visualization_min_tsdf_weight: 0.10000000149011612
    layer_visualization_undo_gamma_correction: false
    lidar_height: 16
    lidar_max_valid_range_m: 50.0
    lidar_min_valid_range_m: 0.10000000149011612
    lidar_vertical_fov_rad: 0.5235987901687622
    lidar_width: 1800
    map_clearing_frame_id: base_link
    map_clearing_radius_m: 5.0
    mapping_type: static_tsdf
    max_angle_above_zero_elevation_rad: 0.2617993950843811
    max_back_projection_distance: 5.0
    maximum_input_queue_length: 10
    min_angle_below_zero_elevation_rad: 0.3490658402442932
    multi_mapper:
      connected_mask_component_size_threshold: 2000
      experimental_use_ground_plane_estimation: false
      ground_points_candidates_max_z_m: 0.15000000596046448
      ground_points_candidates_min_z_m: -0.10000000149011612
      num_ransac_iterations: 1000
      ransac_distance_threshold_m: 0.20000000298023224
      remove_small_connected_components: true
    num_cameras: 1
    output_pessimistic_distance_map: true
    pose_frame: base_link
    print_delays_to_console: false
    print_queue_drops_to_console: false
    print_rates_to_console: false
    print_statistics_on_console_period_ms: 10000
    print_timings_to_console: false
    publish_debug_vis_rate_hz: 2.0
    publish_esdf_distance_slice: true
    publish_layer_rate_hz: 10.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    start_type_description_service: true
    static_mapper:
      check_neighborhood: true
      decay_integrator_deallocate_decayed_blocks: true
      depth_preprocessing_num_dilations: 4
      do_depth_preprocessing: false
      esdf_integrator_max_distance_m: 2.0
      esdf_integrator_max_site_distance_vox: 1.0
      esdf_integrator_min_weight: 9.999999747378752e-05
      esdf_slice_height: 1.0
      esdf_slice_max_height: 1.0
      esdf_slice_min_height: 0.0
      exclude_last_view_from_decay: false
      free_region_decay_probability: 0.550000011920929
      free_region_occupancy_probability: 0.30000001192092896
      lidar_projective_integrator_max_integration_distance_m: 10.0
      max_tsdf_distance_for_occupancy_m: 0.15000000596046448
      max_unobserved_to_keep_consecutive_occupancy_ms: 200
      mesh_integrator_min_weight: 9.999999747378752e-05
      mesh_integrator_weld_vertices: true
      min_consecutive_occupancy_duration_for_reset_ms: 2000
      min_duration_since_occupied_for_freespace_ms: 1000
      occupancy_decay_to_free: false
      occupied_region_decay_probability: 0.4000000059604645
      occupied_region_half_width_m: 0.10000000149011612
      occupied_region_occupancy_probability: 0.699999988079071
      projective_integrator_max_integration_distance_m: 7.0
      projective_integrator_max_weight: 5.0
      projective_integrator_truncation_distance_vox: 4.0
      projective_integrator_weighting_mode: kInverseSquareWeight
      projective_tsdf_integrator_invalid_depth_decay_factor: -1.0
      raycast_subsampling_factor: 4
      slice_height_above_plane_m: 0.0
      slice_height_thickness_m: 0.10000000149011612
      tsdf_decay_factor: 0.949999988079071
      tsdf_decayed_free_distance_vox: 4.0
      tsdf_decayed_weight_threshold: 0.0010000000474974513
      tsdf_set_free_distance_on_decayed: false
      unobserved_region_occupancy_probability: 0.5
      workspace_bounds_max_corner_x_m: 0.0
      workspace_bounds_max_corner_y_m: 2.0
      workspace_bounds_max_height_m: 1.0
      workspace_bounds_min_corner_x_m: 0.0
      workspace_bounds_min_corner_y_m: 2.0
      workspace_bounds_min_height_m: 0.0
      workspace_bounds_type: kUnbounded
    tick_period_ms: 10
    update_esdf_rate_hz: 5.0
    update_mesh_rate_hz: 5.0
    use_color: true
    use_depth: true
    use_lidar: true
    use_non_equal_vertical_fov_lidar_params: false
    use_segmentation: false
    use_sim_time: false
    use_tf_transforms: true
    use_topic_transforms: false
    voxel_size: 0.05000000074505806
    workspace_height_bounds_visualization_attachment_frame_id: base_link
    workspace_height_bounds_visualization_side_length: 10.0

